/**
 * DEXA Blog — Client-side markdown blog engine
 * posts.json is auto-generated by build.js from posts/*.md frontmatter
 */

(function () {
    const POSTS_JSON = 'posts.json';
    const POSTS_DIR = 'posts/';

    const isPostPage = window.location.pathname.includes('post.html');

    // ─── Utilities ───

    async function fetchPosts() {
        try {
            const res = await fetch(POSTS_JSON);
            if (!res.ok) throw new Error('Fetch failed');
            return await res.json();
        } catch (e) {
            console.warn('Failed to load posts.json:', e);
            return [];
        }
    }

    // Strip Obsidian YAML frontmatter and clean syntax
    function cleanMarkdown(md) {
        md = md.replace(/^---[\s\S]*?---\n*/m, '');
        md = md.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2');
        md = md.replace(/\[\[([^\]]+)\]\]/g, '$1');
        md = md.replace(/^> \[!(\w+)\]\s*(.*)$/gm, '> **$2**');
        return md;
    }

    function formatDate(dateStr) {
        const d = new Date(dateStr + 'T00:00:00');
        return d.toLocaleDateString('ko-KR', {
            year: 'numeric', month: 'long', day: 'numeric'
        });
    }

    function getSlugFromURL() {
        return new URLSearchParams(window.location.search).get('slug');
    }

    function getCategoryColor(category) {
        const colors = {
            'Article': '#00F0FF',
            'Tech': '#00F0FF',
            'Project': '#BC13FE',
            'Thought': '#39FF14',
            'Tutorial': '#39FF14',
            'News': '#E50914',
        };
        return colors[category] || '#00F0FF';
    }

    // ─── Blog Listing Page ───

    async function initBlogList() {
        const posts = await fetchPosts();
        if (!posts.length) {
            const grid = document.getElementById('post-grid');
            if (grid) grid.innerHTML = `
                <div class="col-span-full text-center py-20">
                    <span class="material-symbols-outlined text-4xl text-gray-700 mb-4">article</span>
                    <p class="text-gray-600 font-mono text-sm">No posts yet.</p>
                    <p class="text-gray-700 font-mono text-xs mt-2">Run <code class="text-[#00F0FF]">node blog/build.js</code> to generate posts.json</p>
                </div>`;
            return;
        }
        posts.sort((a, b) => new Date(b.date) - new Date(a.date));
        buildFilters(posts);
        renderPostCards(posts);
    }

    function buildFilters(posts) {
        const filterBar = document.getElementById('filter-bar');
        if (!filterBar) return;

        const categories = [...new Set(posts.map(p => p.category))];
        categories.forEach(cat => {
            const btn = document.createElement('button');
            btn.className = 'filter-btn px-4 py-2 text-xs font-mono uppercase tracking-wider border border-white/20 rounded-sm transition-all hover:border-[#00F0FF] hover:text-[#00F0FF]';
            btn.dataset.filter = cat;
            btn.textContent = cat;
            filterBar.appendChild(btn);
        });

        filterBar.addEventListener('click', (e) => {
            const btn = e.target.closest('.filter-btn');
            if (!btn) return;
            filterBar.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            const filter = btn.dataset.filter;
            document.querySelectorAll('.post-card').forEach(card => {
                card.style.display = (filter === 'all' || card.dataset.category === filter) ? '' : 'none';
            });
        });
    }

    function renderPostCards(posts) {
        const grid = document.getElementById('post-grid');
        if (!grid) return;
        grid.innerHTML = '';

        posts.forEach(post => {
            const color = getCategoryColor(post.category);
            const card = document.createElement('a');
            card.href = `post.html?slug=${encodeURIComponent(post.slug)}`;
            card.className = 'post-card card-hover-effect block bg-[#0A0A0A] border border-white/10 rounded-xl overflow-hidden group';
            card.dataset.category = post.category;

            card.innerHTML = `
                ${post.thumbnail
                    ? `<div class="aspect-video overflow-hidden bg-[#111]">
                        <img src="${post.thumbnail}" alt="${post.title}" class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500">
                       </div>`
                    : `<div class="aspect-video bg-gradient-to-br from-[#111] to-[#0A0A0A] flex items-center justify-center relative overflow-hidden">
                        <div class="absolute inset-0 opacity-20" style="background: radial-gradient(circle at 30% 40%, ${color}22, transparent 70%)"></div>
                        <span class="material-symbols-outlined text-5xl text-gray-800 group-hover:text-[${color}] transition-colors duration-300">article</span>
                       </div>`
                }
                <div class="p-6">
                    <div class="flex items-center gap-3 mb-3">
                        <span class="text-xs font-mono uppercase tracking-widest px-2 py-0.5 rounded-sm border"
                            style="color: ${color}; border-color: ${color}33; background: ${color}11">
                            ${post.category}
                        </span>
                        <span class="text-xs text-gray-600 font-mono">${formatDate(post.date)}</span>
                    </div>
                    <h3 class="text-lg font-bold text-white mb-2 group-hover:text-[#00F0FF] transition-colors leading-snug">
                        ${post.title}
                    </h3>
                    <p class="text-sm text-gray-500 leading-relaxed line-clamp-2">
                        ${post.description}
                    </p>
                    <div class="flex flex-wrap gap-1.5 mt-4">
                        ${post.tags.map(tag => `<span class="text-[10px] font-mono text-gray-600 bg-white/5 px-2 py-0.5 rounded">${tag}</span>`).join('')}
                    </div>
                    <div class="mt-4 flex items-center gap-1 text-xs font-mono text-gray-600 group-hover:text-[#00F0FF] transition-colors">
                        Read more <span class="material-symbols-outlined text-sm">arrow_forward</span>
                    </div>
                </div>`;
            grid.appendChild(card);
        });
    }

    // ─── Post Viewer Page ───

    async function initPostView() {
        const slug = getSlugFromURL();
        if (!slug) { window.location.href = 'index.html'; return; }

        const posts = await fetchPosts();
        posts.sort((a, b) => new Date(b.date) - new Date(a.date));

        const postIndex = posts.findIndex(p => p.slug === slug);
        const post = posts[postIndex];

        if (!post) {
            document.getElementById('post-content').innerHTML = `
                <div class="text-center py-20">
                    <span class="material-symbols-outlined text-5xl text-gray-700 mb-4">error_outline</span>
                    <p class="text-gray-500 font-mono">Post not found.</p>
                    <a href="index.html" class="inline-block mt-4 text-[#00F0FF] font-mono text-sm hover:underline">Back to Blog</a>
                </div>`;
            return;
        }

        document.title = `${post.title} | DEXA Blog`;

        const color = getCategoryColor(post.category);
        document.getElementById('post-category').textContent = post.category;
        document.getElementById('post-category').style.color = color;
        document.getElementById('post-category').style.borderColor = color + '55';
        document.getElementById('post-category').style.background = color + '11';
        document.getElementById('post-date').textContent = formatDate(post.date);

        document.getElementById('post-tags').innerHTML = post.tags.map(tag =>
            `<span class="text-[10px] font-mono text-gray-600 bg-white/5 px-2 py-0.5 rounded">${tag}</span>`
        ).join('');

        // Fetch markdown — try encoded filename, then raw, then BLOG_CONTENT global
        const filename = post.file || (slug + '.md');
        let mdText = null;
        for (const url of [POSTS_DIR + encodeURIComponent(filename), POSTS_DIR + filename]) {
            try {
                const res = await fetch(url);
                if (res.ok) { mdText = await res.text(); break; }
            } catch (e) { /* next */ }
        }
        if (!mdText && typeof BLOG_CONTENT !== 'undefined' && BLOG_CONTENT[slug]) {
            mdText = BLOG_CONTENT[slug];
        }

        if (mdText) {
            document.getElementById('post-content').innerHTML = marked.parse(cleanMarkdown(mdText));
        } else {
            document.getElementById('post-content').innerHTML = `
                <div class="text-center py-20">
                    <span class="material-symbols-outlined text-5xl text-gray-700 mb-4">error_outline</span>
                    <p class="text-gray-500 font-mono">Failed to load post content.</p>
                    <p class="text-gray-700 font-mono text-xs mt-2">로컬 테스트: <code class="text-[#00F0FF]">npx serve .</code> (adxdeck 폴더에서)</p>
                </div>`;
        }

        // Post navigation
        if (posts.length > 1) {
            const nav = document.getElementById('post-nav');
            nav.classList.remove('hidden');
            const prevLink = document.getElementById('prev-post');
            const nextLink = document.getElementById('next-post');

            if (postIndex < posts.length - 1) {
                const prev = posts[postIndex + 1];
                prevLink.href = `post.html?slug=${encodeURIComponent(prev.slug)}`;
                document.getElementById('prev-title').textContent = prev.title;
            } else { prevLink.style.visibility = 'hidden'; }

            if (postIndex > 0) {
                const next = posts[postIndex - 1];
                nextLink.href = `post.html?slug=${encodeURIComponent(next.slug)}`;
                document.getElementById('next-title').textContent = next.title;
            } else { nextLink.style.visibility = 'hidden'; }
        }
    }

    // ─── Mobile Menu ───

    function initMobileMenu() {
        const btn = document.getElementById('mobile-menu-btn');
        const menu = document.getElementById('mobile-menu');
        if (btn && menu) btn.addEventListener('click', () => menu.classList.toggle('hidden'));
    }

    // ─── Init ───

    document.addEventListener('DOMContentLoaded', () => {
        initMobileMenu();
        isPostPage ? initPostView() : initBlogList();
    });
})();
