/**
 * DEXA Blog — Client-side markdown blog engine
 * posts.json is auto-generated by build.js from posts/*.md frontmatter
 */

(function () {
    const POSTS_JSON = 'posts.json';
    const POSTS_DIR = 'posts/';
    const TRACK_LABELS = Object.freeze({
        'media-art': 'Media Art',
        'ai-ax': 'AI · AX'
    });
    const VALID_TRACKS = new Set(Object.keys(TRACK_LABELS));

    const isPostPage = window.location.pathname.includes('post.html');

    // ─── Utilities ───

    async function fetchPosts() {
        try {
            const res = await fetch(POSTS_JSON);
            if (!res.ok) throw new Error('Fetch failed');
            return await res.json();
        } catch (e) {
            console.warn('Failed to load posts.json:', e);
            return [];
        }
    }

    // Strip Obsidian YAML frontmatter and clean syntax
    function cleanMarkdown(md) {
        md = md.replace(/^---[\s\S]*?---\n*/m, '');
        md = md.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2');
        md = md.replace(/\[\[([^\]]+)\]\]/g, '$1');
        md = md.replace(/^> \[!(\w+)\]\s*(.*)$/gm, '> **$2**');
        return md;
    }

    function formatDate(dateStr) {
        return String(dateStr || '').replace(/-/g, '.');
    }

    function getSlugFromURL() {
        return new URLSearchParams(window.location.search).get('slug');
    }

    function escapeHtml(value) {
        return String(value || '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }

    function blogAssetUrl(value) {
        const url = String(value || '');
        if (/^(https?:|\/)/i.test(url)) return url;
        return `/blog/${url.replace(/^\.?\//, '').replace(/^blog\//, '')}`;
    }

    // ─── Blog Listing Page ───

    async function initBlogList() {
        const grid = document.getElementById('post-grid');
        const hasStaticPosts = !!grid?.querySelector('.post-card');
        const posts = await fetchPosts();
        if (!posts.length) {
            if (!hasStaticPosts && grid) grid.innerHTML = `
                <div style="grid-column:1/-1;text-align:center;padding:80px 0;">
                    <p class="mono" style="color:var(--muted);font-size:13px;">No posts yet.</p>
                    <p class="mono" style="color:var(--muted);font-size:11px;margin-top:8px;">Run <code style="background:var(--panel);border:1px solid var(--line);border-radius:4px;padding:2px 6px;">node blog/build.js</code> to generate posts.json</p>
                </div>`;
            buildFilters();
            return;
        }
        posts.sort((a, b) => new Date(b.date) - new Date(a.date));
        if (!hasStaticPosts) renderPostCards(posts);
        buildFilters();
    }

    function buildFilters() {
        const filterBar = document.getElementById('filter-bar');
        if (!filterBar) return;

        const applyFilter = (filter, updateUrl = false) => {
            const resolved = VALID_TRACKS.has(filter) ? filter : 'all';
            filterBar.querySelectorAll('.dx-tag-chip').forEach(button => {
                const isActive = button.dataset.filter === resolved;
                button.classList.toggle('active', isActive);
                button.setAttribute('aria-pressed', isActive ? 'true' : 'false');
            });
            document.querySelectorAll('#post-grid .post-card').forEach(card => {
                card.hidden = resolved !== 'all' && card.dataset.track !== resolved;
            });

            if (updateUrl) {
                const url = new URL(window.location.href);
                if (resolved === 'all') url.searchParams.delete('track');
                else url.searchParams.set('track', resolved);
                window.history.replaceState(null, '', url);
            }
        };

        filterBar.addEventListener('click', (e) => {
            const btn = e.target.closest('.dx-tag-chip');
            if (!btn || !filterBar.contains(btn)) return;
            applyFilter(btn.dataset.filter, true);
        });

        const requestedTrack = new URLSearchParams(window.location.search).get('track');
        applyFilter(requestedTrack || 'all');
    }

    function renderPostCards(posts) {
        const grid = document.getElementById('post-grid');
        if (!grid) return;
        grid.innerHTML = '';

        posts.forEach(post => {
            const card = document.createElement('a');
            card.href = `/blog/posts/${encodeURIComponent(post.slug)}/`;
            card.className = 'post-card panel-card';
            card.dataset.track = post.track;
            card.dataset.category = post.category;
            card.setAttribute('aria-label', `Read ${post.title}`);

            const trackLabel = post.trackLabel || TRACK_LABELS[post.track] || post.track;

            card.innerHTML = `
                ${post.thumbnail
                    ? `<div class="card-frame"><img src="${escapeHtml(blogAssetUrl(post.thumbnail))}" alt="${escapeHtml(post.title)}" loading="lazy"></div>`
                    : ''
                }
                <span class="dx-meta"><span class="dx-badge">${escapeHtml(trackLabel)}</span><span class="dx-date">${escapeHtml(post.category)} · ${formatDate(post.date)}</span></span>
                <h3>${escapeHtml(post.title)}</h3>
                <p>${escapeHtml(post.description)}</p>
                <span class="dx-more">READ MORE →</span>`;
            grid.appendChild(card);
        });
    }

    // ─── Post Viewer Page ───

    async function initPostView() {
        const slug = getSlugFromURL();
        if (!slug) { window.location.href = 'index.html'; return; }

        // Legacy query-string viewer now forwards to the static SEO URL.
        window.location.replace(`/blog/posts/${encodeURIComponent(slug)}/`);
        return;

        const posts = await fetchPosts();
        posts.sort((a, b) => new Date(b.date) - new Date(a.date));

        const postIndex = posts.findIndex(p => p.slug === slug);
        const post = posts[postIndex];

        if (!post) {
            document.getElementById('post-content').innerHTML = `
                <div style="text-align:center;padding:80px 0;">
                    <p class="mono" style="color:var(--muted);">Post not found.</p>
                    <a href="index.html" class="btn-ghost">Back to Blog</a>
                </div>`;
            return;
        }

        document.title = `${post.title} | DEXA Blog`;

        document.getElementById('post-category').textContent = post.category;
        document.getElementById('post-category').className = 'dx-badge';
        document.getElementById('post-date').textContent = formatDate(post.date);
        document.getElementById('post-date').className = 'dx-date';

        document.getElementById('post-tags').innerHTML = post.tags.map(tag =>
            `<span class="dx-tag-chip">${tag}</span>`
        ).join('');

        // Fetch markdown content
        const filename = post.file || (slug + '.md');
        let mdText = null;
        try {
            const res = await fetch(POSTS_DIR + filename);
            if (res.ok) mdText = await res.text();
        } catch (e) { /* fallback below */ }
        if (!mdText && typeof BLOG_CONTENT !== 'undefined' && BLOG_CONTENT[slug]) {
            mdText = BLOG_CONTENT[slug];
        }

        if (mdText) {
            document.getElementById('post-content').innerHTML = marked.parse(cleanMarkdown(mdText));
        } else {
            document.getElementById('post-content').innerHTML = `
                <div style="text-align:center;padding:80px 0;">
                    <p class="mono" style="color:var(--muted);">Failed to load post content.</p>
                    <p class="mono" style="color:var(--muted);font-size:11px;margin-top:8px;">로컬 테스트: <code style="background:var(--panel);border:1px solid var(--line);border-radius:4px;padding:2px 6px;">npx serve .</code> (adxdeck 폴더에서)</p>
                </div>`;
        }

        // Post navigation
        if (posts.length > 1) {
            const nav = document.getElementById('post-nav');
            nav.classList.remove('hidden');
            const prevLink = document.getElementById('prev-post');
            const nextLink = document.getElementById('next-post');

            if (postIndex < posts.length - 1) {
                const prev = posts[postIndex + 1];
                prevLink.href = `/blog/posts/${encodeURIComponent(prev.slug)}/`;
                document.getElementById('prev-title').textContent = prev.title;
            } else { prevLink.style.visibility = 'hidden'; }

            if (postIndex > 0) {
                const next = posts[postIndex - 1];
                nextLink.href = `/blog/posts/${encodeURIComponent(next.slug)}/`;
                document.getElementById('next-title').textContent = next.title;
            } else { nextLink.style.visibility = 'hidden'; }
        }
    }

    // ─── Mobile Menu ───

    function initMobileMenu() {
        const btn = document.getElementById('mobile-menu-btn');
        const menu = document.getElementById('mobile-menu');
        if (btn && menu) btn.addEventListener('click', () => {
            const open = menu.classList.toggle('hidden') === false;
            btn.setAttribute('aria-expanded', open ? 'true' : 'false');
            btn.setAttribute('aria-label', open ? 'Close navigation menu' : 'Open navigation menu');
        });
    }

    // ─── Init ───

    document.addEventListener('DOMContentLoaded', () => {
        initMobileMenu();
        isPostPage ? initPostView() : initBlogList();
    });
})();
